# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Dependabot help page:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2/
  jboss-public-repository-group:
    type: maven-repository
    url: https://repository.jboss.org/nexus/content/groups/public/
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
      # time: "07:48" # current UTC time: https://www.google.com/search?q=current+utc+time
    ignore:
      # Bom built in createSnapshots.groovy script in TS:
      - dependency-name: 'org.wildfly.bom:wildfly-ee'
    rebase-strategy: "disabled"
    open-pull-requests-limit: 20
    registries:
      - maven-central
      - jboss-public-repository-group
  - package-ecosystem: "maven"
    directory: "/basic/pom-wildfly-client"
    schedule:
      interval: "daily"
      # time: "07:48" # current UTC time: https://www.google.com/search?q=current+utc+time
    ignore:
      # Bom version built in createSnapshots.groovy script in TS:
      - dependency-name: 'org.wildfly.bom:wildfly-ee'
    rebase-strategy: "disabled"
    open-pull-requests-limit: 20
    registries:
      - maven-central
      - jboss-public-repository-group
  - package-ecosystem: "maven"
    directory: "/multinode/pom-wildfly-client"
    schedule:
      interval: "daily"
      # time: "07:48" # current UTC time: https://www.google.com/search?q=current+utc+time
    ignore:
      # Bom version built in createSnapshots.groovy script in TS:
      - dependency-name: 'org.wildfly.bom:wildfly-ee'
    rebase-strategy: "disabled"
    open-pull-requests-limit: 20
    registries:
      - maven-central
      - jboss-public-repository-group
